name: flutter_project
description: Base Flutter Project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  get: ^4.6.5
  injectable: ^2.1.0
  multiple_result: ^4.0.0
  event_bus_plus: ^0.6.1
  pretty_dio_logger: ^1.1.1
  flutter_pretty_dio_logger: ^2.0.3
  dio_smart_retry: ^1.0.0
  logger: ^1.1.0
  shared_preferences: ^2.0.15
  json_annotation: ^4.7.0
  dio: ^4.0.6
  retrofit: ^3.3.1
  path_provider: ^2.0.11
  realm: ^1.0.0
  flutter_svg: ^1.1.6
  adaptive_theme:
    git: git@github.com:hacnguyen1412/adaptive_theme.git
    
  flutter_sheet_localization:
    git:
      url: git@github.com:hacnguyen1412/flutter_sheet_localization.git
      path: flutter_sheet_localization
  auto_route: ^5.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable:
  auto_route_generator:
  retrofit_generator:
  flutter_sheet_localization_generator:
    git:
      url: git@github.com:hacnguyen1412/flutter_sheet_localization.git
      path: flutter_sheet_localization_generator
  mockito: ^5.3.2


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
